local Lib=loadstring(game:HttpGet("https://raw.githubusercontent.com/Cowrod/UI-Lib/main/Source.lua"))()
Lib.Title("Library Test")
Lib.Tab("Test")
Lib.Button("Button",function()
	print("Clicked To Button!")
end,"Test",true)
Lib.Toggle("Toggle",function(t)
	print("Toggle Changed: "..tostring(t))
	-- If You Are Gona Print Result Put Value In tostring()
	-- For Some Reason Its Broken For Me
end,"Test",true,false)
Lib.TextBox("TextBox",function(t)
	print("Text Edited: "..t)
end,"Test",true)
Lib.Space("Test")
Lib.Label("Label","Test",true)
