local Lib=loadstring(game:HttpGet("https://raw.githubusercontent.com/Cowrod/UI-Lib/main/Source.lua"))()
Lib.Title("Library Test")
local tab = Lib.Tab("Test")
tab:Button("Button",function()
	print("Clicked To Button!")
end)
tab:Toggle("Toggle",false,function(t)
	print("Toggle Changed: "..tostring(t))
	-- If You Are Gona Print Result Put Value In tostring()
	-- For Some Reason Its Broken For Me
end)
tab:TextBox("TextBox",function(t)
	print("Text Edited: "..t)
end)
tab:Space()
tab:Label("Label")
