local Lib=loadstring(game:HttpGet("https://raw.githubusercontent.com/Cowrod/UI-Lib/main/Source.lua"))()
Lib.Title("Library Test")
local tab = Lib.CreateTab("Test")
tab:Button("Button",function()
	print("Clicked To Button!")
end)
tab:Toggle("Toggle",false,function(t)
	print("Toggle Changed: "..tostring(t))
end)
tab:TextBox("TextBox",function(t)
	print("Text Edited: "..t)
end)
tab:Space()
tab:Label("Label")
